### ISSUE TITLE
Unknown function taggatron#UpdateTags on saving a file

### ISSUE THREAD

**Issue by mschaaf** [joonty/vim-taggatron#10]
With vim 8 on save I get the error message "Unknown function taggatron#UpdateTags"
I index java and javascript files and get it for both.
A call to TagUpdate works.

**Comment by mschaaf** [comment]
This happens if your vim didn't support python at all or only python3 like in my case. I created a pull request to change the plugin from python to python3.

https://github.com/joonty/vim-taggatron/pull/11

**Comment by Roy-Orbison** [comment]
I compiled 8.2 myself and now see this error too, even though it has both python versions as far as I can tell. Relevant column of `:version`:

``` none
+postscript
+printer
+profile
+python/dyn
+python3/dyn
+quickfix
+reltime
+rightleft
-ruby
+scrollbind
+signs
```

**Comment by jp-hoehmann** [comment]
I think you may be encountering a common pitfall: Vim may be compiled with both Python2 and Python3, but only one can be active at a time. Whatever version is used first will win and attempting to use the other version will result in errors.

Try putting this in your vimrc before loading any plugins:
```
if has('python')
endif
```

This looks like it should have no effect, but it will access Python2, and thus force all the plugins to run with Python2. Without this line, what version of Python is available will depend on whatever version the first plugin you load tries first.

Slightly more detail here: https://robertbasic.com/blog/force-python-version-in-vim/

**Comment by Roy-Orbison** [comment]
Yeah, I need Python 3 for another plugin. I'm using @mschaaf's repo with the `issue/10` branch checked out and frozen, and it seems to be fine. Would be nice if this repo had the Python 2 version branched off for legacy use and this commit was merged here.

**Comment by joonty** [comment]
This has now been fixed - if your vim uses python 3 you can switch to the `python3` branch of this repository.
